apiVersion: v1
kind: ConfigMap
metadata:
  name: resources-ms-config
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "k8s-helm-chart.configMapLabels" . | nindent 4 }}
data:
  RESOURCES_DB_URL: "resources-db"
  RESOURCES_DB_PORT: "5432"
  DATABASE_NAME: "resources_db"
  SONGS_MS_URL: "songs-ms"
  SONGS_MS_PORT: "8081"
  RESOURCES_MS_PORT: "8080"
