# Resources Microservice Service
apiVersion: v1
kind: Service
metadata:
  name: resources-ms
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort # external traffic has access to 8081 on each worker node
  ports:
    - port: 8080 # the "outside" port for incoming requests, mapped to the targetPort of pod
      targetPort: 8080 # the port ot apps container is listening at (matches containerPort in Deployment)
      nodePort: 30080 # Custom port for node testing
  selector:
    app: resources-ms
---
# Resources Microservice Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: resources-ms
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: resources-ms
  template:
    metadata:
      labels:
        app: resources-ms
    spec:
      containers:
        - name: resources-ms
          image: resources-image:v3
          imagePullPolicy: IfNotPresent # to look the image at the local Docker daemon
          ports:
            - containerPort: 8080 # the port of the app that is running in the container
          envFrom:
            - configMapRef:
                name: resources-ms-config
          env:
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-username
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: postgres-password
          startupProbe:
            httpGet:
              path: /actuator/health
              port: 8080
            failureThreshold: 30
            periodSeconds: 5
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 2
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            periodSeconds: 5
            timeoutSeconds: 2
            failureThreshold: 3
